db:
  image: library/mysql:5.6.22
  ports:
    - "13307:3306"
  environment:
    MYSQL_DATABASE: 'tabs_dev'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: 'pass'
    MYSQL_ROOT_PASSWORD: 'pass'
web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "8080:3000"
  links:
    - db

